export const METADATA_REQUEST_DELAY_MS = 1500;
export const METADATA_REQUEST_TIMEOUT_MS = 10_000;
export const METADATA_CACHE_TTL_DAYS = 7;
export const METADATA_MAX_RETRIES = 3;
export const METADATA_BACKOFF_BASE_MS = 30_000;
